update bblfsh client-go
Signed-off-by: Maxim Sukharev <maxim@sourced.tech>

diff --git a/vendor/gopkg.in/bblfsh/client-go.v2/Makefile b/vendor/gopkg.in/bblfsh/client-go.v2/Makefile
--- a/vendor/gopkg.in/bblfsh/client-go.v2/Makefile
+++ b/vendor/gopkg.in/bblfsh/client-go.v2/Makefile
@@ -6,8 +6,10 @@ GOPATH ?= $(shell go env GOPATH)
 TOOLS_FOLDER = tools
 
 ifneq ($(OS),Windows_NT)
+UNAME := $(shell uname)
 COPY = cp
 else
+UNAME := Windows_NT
 COPY = copy
 endif
 
@@ -26,17 +28,34 @@ clean: clean-libuast
 clean-libuast:
 	find ./  -regex '.*\.[h,c]c?' ! -name 'bindings.h' -exec rm -f {} +
 
-ifneq ($(OS),Windows_NT)
-cgo-dependencies:
-	curl -SL https://github.com/bblfsh/libuast/releases/download/v$(LIBUAST_VERSION)/libuast-v$(LIBUAST_VERSION).tar.gz | tar xz
-	mv libuast-v$(LIBUAST_VERSION)/src/* $(TOOLS_FOLDER)/.
-	rm -rf libuast-v$(LIBUAST_VERSION)
-else
+ifeq ($(OS),Windows_NT)
 cgo-dependencies:
 	go get -v github.com/mholt/archiver/cmd/archiver
 	cd $(TOOLS_FOLDER) && \
 	curl -SLko binaries.win64.mingw.zip https://github.com/bblfsh/libuast/releases/download/v$(LIBUAST_VERSION)/binaries.win64.mingw.zip && \
 	$(GOPATH)\bin\archiver open binaries.win64.mingw.zip && \
 	del /q binaries.win64.mingw.zip && echo done
-endif  # !Windows_NT
+else
+ifeq ($(UNAME),Darwin)
+cgo-dependencies: unix-dependencies
+else
+cgo-dependencies: | check-gcc unix-dependencies
+check-gcc:
+	@if \
+		[[ -z `which gcc` ]] || \
+		[[ -z `which g++` ]] || \
+		[[ 5 -gt `gcc -dumpversion | sed -r 's/^[^0-9]*([0-9]+).*/\1/g'` ]] || \
+		[[ 5 -gt `g++ -dumpversion | sed -r 's/^[^0-9]*([0-9]+).*/\1/g'` ]]; \
+	then \
+		echo -e "error; GCC and G++ v5 or greater are required \n"; \
+		echo -e "- GCC: `gcc --version` \n"; \
+		echo -e "- G++: `g++ --version` \n"; \
+		exit 1; \
+	fi;
+endif
+endif
 
+unix-dependencies:
+	curl -SL https://github.com/bblfsh/libuast/releases/download/v$(LIBUAST_VERSION)/libuast-v$(LIBUAST_VERSION).tar.gz | tar xz
+	mv libuast-v$(LIBUAST_VERSION)/src/* $(TOOLS_FOLDER)/.
+	rm -rf libuast-v$(LIBUAST_VERSION)
